const wordList = [
    { word: "doremon", display: "Doremon", hint: "Chú mèo máy đến từ thế kỷ 22, nhân vật chính của bộ truyện." },
    { word: "nobita", display: "Nobita", hint: "Cậu bé hậu đậu, bạn thân của Doremon." },
    { word: "shizuka", display: "Shizuka", hint: "Cô bé dịu dàng, học giỏi, là vợ tương lai của Nobita." },
    { word: "chaien", display: "Chaien", hint: "Cậu bé to lớn, hay bắt nạt bạn bè, thích hát nhưng hát rất dở." },
    { word: "xeko", display: "Xeko", hint: "Cậu bé giàu có, kiêu ngạo, thường khoe khoang với bạn bè." },
    { word: "chongchongtre", display: "Chong Chóng Tre", hint: "Bảo bối giúp bay lên trời, rất nổi tiếng của Doremon." },
    { word: "canhcuthanky", display: "Cánh Cửa Thần Kỳ", hint: "Bảo bối giúp đi đến bất cứ nơi nào chỉ bằng một cánh cửa." },
    { word: "comaythoigian", display: "Cỗ Máy Thời Gian", hint: "Bảo bối giúp di chuyển đến quá khứ hoặc tương lai." },
    { word: "banhran", display: "Bánh Rán", hint: "Món ăn yêu thích của Doremon." },
    { word: "menobita", display: "Mẹ Nobita", hint: "Người thường xuyên la mắng Nobita vì học kém và hậu đậu." },
    { word: "dekisugi", display: "Dekisugi", hint: "Cậu bé học giỏi, thông minh, bạn của Nobita và Shizuka." },
    { word: "gian", display: "Gian", hint: "Tên gọi khác của Chaien trong một số bản dịch." },
    { word: "suneo", display: "Suneo", hint: "Tên gọi khác của Xeko trong một số bản dịch." },
    { word: "tuonglai", display: "Tương Lai", hint: "Nơi Doremon xuất phát để giúp Nobita thay đổi số phận." },
    { word: "tuithanky", display: "Túi Thần Kỳ", hint: "Nơi Doremon lấy ra các bảo bối giúp Nobita." },
    { word: "meomay", display: "Mèo Máy", hint: "Loài của Doremon, được sản xuất ở thế kỷ 22." },
    { word: "giadinhnobi", display: "Gia Đình Nobi", hint: "Gia đình của Nobita, gồm bố, mẹ và Nobita." },
    { word: "tam", display: "Tắm", hint: "Hoạt động yêu thích của Shizuka, thường bị các bạn làm phiền." },
    { word: "truonghoc", display: "Trường Học", hint: "Nơi các bạn thường gặp nhau và xảy ra nhiều câu chuyện hài hước." },
    { word: "doremi", display: "Doremi", hint: "Em gái của Doremon, xuất hiện trong một số tập đặc biệt." },
    { word: "denpinthunho", display: "Đèn Pin Thu Nhỏ", hint: "Bảo bối giúp thu nhỏ mọi vật khi chiếu vào." },
    { word: "denpinphongto", display: "Đèn Pin Phóng To", hint: "Bảo bối giúp phóng to mọi vật khi chiếu vào." },
    { word: "canhcuididaucungduoc", display: "Cánh Cửa Đi Đâu Cũng Được", hint: "Bảo bối giúp đi đến bất kỳ nơi nào mong muốn." },
    { word: "banhmighinho", display: "Bánh Mì Ghi Nhớ", hint: "Bảo bối giúp ghi nhớ nội dung sách vở khi dán lên." },
    { word: "sungbankhongkhi", display: "Súng Bắn Không Khí", hint: "Bảo bối dùng để bắn luồng không khí mạnh." },
    { word: "caphiendich", display: "Cá Phiên Dịch", hint: "Bảo bối giúp hiểu được mọi ngôn ngữ." },
    { word: "robotsaochép", display: "Robot Sao Chép", hint: "Bảo bối tạo ra bản sao của người sử dụng." },
    { word: "mayanhthaydo", display: "Máy Ảnh Thay Đồ", hint: "Bảo bối giúp thay đổi trang phục chỉ bằng một bức ảnh." },
    { word: "khantthoigian", display: "Khăn Thời Gian", hint: "Bảo bối giúp làm mới hoặc làm cũ vật thể khi phủ lên." },
    { word: "vongdeoxyentuong", display: "Vòng Đeo Xuyên Tường", hint: "Bảo bối giúp đi xuyên qua các vật thể rắn." },
    { word: "sontrongluc", display: "Sơn Trọng Lực", hint: "Bảo bối giúp thay đổi trọng lực của vật thể." },
    { word: "aochoangtanghinh", display: "Áo Choàng Tàng Hình", hint: "Bảo bối giúp người dùng trở nên vô hình." },
    { word: "chongchongbay", display: "Chong Chóng Bay", hint: "Bảo bối giúp bay lơ lửng trên không." },
    { word: "gangtaysieuluc", display: "Găng Tay Siêu Lực", hint: "Bảo bối giúp tăng sức mạnh cho người sử dụng." },
    { word: "hopthoiet", display: "Hộp Thời Tiết", hint: "Bảo bối giúp điều chỉnh thời tiết theo ý muốn." },
    { word: "maytaogiacmo", display: "Máy Tạo Giấc Mơ", hint: "Bảo bối giúp tạo ra giấc mơ theo ý muốn." },
    { word: "keothaydoitamtrang", display: "Kẹo Thay Đổi Tâm Trạng", hint: "Bảo bối giúp thay đổi cảm xúc của người ăn." },
    { word: "dungdichnhanban", display: "Dung Dịch Nhân Bản", hint: "Bảo bối giúp tạo ra bản sao của vật thể." }
];
